print('Course plan (Part one):')
lessons_list = \
    ['1. Basic facts',
     '2. Install Python',
     '3. Install Pycharm',
     '4. Syntax',
     '5. Int. Operators',
     '6. Variables',
     '7. Boolean data type',
     '8. Strings data type',
     '9. Operations with strings',
     '10. Strings methods',
     '11. Format strings',
     '12. IF',
     '13. For, While',
     '14. Lists',
     '15. Home work',
     '16. Lists methods',
     '17. Mutable and unmutabla data types',
     '18. Home work',
     '19. Home work done',
     '20. Tuples',
     '21. Home work done',
     '22. Sets',
     '23. Dictionaries',
     '24. Dictionaries methods',
     '25. Game "Gues a number"',
     '26. Functions part 1',
     '27. Functions part 2',
     '28. Functions part 3',
     '29. Home work done',
     '30. Modules',
     '31. Datetime Module',
     '32. Home work done',
     '33. Work with files',
     '34. Parsing',
     '35. Syntax errors and exceptions',
     '36. Basic OOP',
     '37. Constructors of Class',
     '38. Incapsulation',
     '39. Parsings Class',
     '40. Inheritance',
     '41. Polymorphism',
     '42. Decorators',
     '43. Lambda functions',
     '44. Regular expressions',
     '45. Module SQLite Part 1',
     '46. Module SQLite Part 2',
     '47. Module SQLite Part 7',
     '48. Module ZipFile']

for i in lessons_list:
    print('---> ', i)